import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMKN 4 BDL
 */
public class admin_page extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    ResultSet RsSiswa = null;
    
    /**
     * Creates new form admin_page
     */
    public admin_page() {
        initComponents();
        String nama=usersession.get_nama();
        
        
//        title.setText(nama);
//        title.setText(nama);
//
//        if("Nama Anda".equals(title.getText())){ // Menggunakan equals() untuk membandingkan String
//            login loginFrame = new login();
//            loginFrame.setVisible(true);
//            dispose(); // Tutup halaman admin saat ini
//            return; // Keluar dari konstruktor
//        }

        // Jika bukan "Nama Anda", maka lanjutkan dengan menampilkan halaman admin
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();

        if(frameSize.height > screenSize.height){
            frameSize.height = screenSize.height;
        }
        if(frameSize.width > screenSize.width){
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                        (screenSize.height - frameSize.height) / 2);

        tampilData();
    }
    
    private static Connection mysqlconfig;
    
    public static Connection configDB() throws SQLException{
        try{
            String url="jdbc:mysql://localhost:3306/needbook";
            String user="root";
            String password="";
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            mysqlconfig = DriverManager.getConnection(url, user, password);
        }catch(Exception e){
            System.err.println("koneksi gagal");
        }
        return mysqlconfig;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_judul = new javax.swing.JTextField();
        input_pengarang = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_buku = new javax.swing.JTable();
        select_kategori = new javax.swing.JComboBox<>();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Pengarang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Kategori");

        btn_tambah.setBackground(new java.awt.Color(0, 0, 0));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "JUDUL", "KATEGORI", "PENGARANG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_buku);
        if (table_buku.getColumnModel().getColumnCount() > 0) {
            table_buku.getColumnModel().getColumn(0).setResizable(false);
        }

        select_kategori.setForeground(new java.awt.Color(255, 255, 255));
        select_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "komik", "novel", "pendidikan", "sejarah" }));

        btn_hapus.setBackground(new java.awt.Color(0, 0, 0));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(0, 0, 0));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("NeedBook");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Judul");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(input_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(select_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(select_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(239, 239, 239))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        tambahData();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void table_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bukuMouseClicked
        tblKeForm();
    }//GEN-LAST:event_table_bukuMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        hapusData();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        editData();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tambahData(){
        String judul, pengarang, kategori;
        judul = input_judul.getText();
        pengarang =  input_pengarang.getText();
        kategori =  select_kategori.getSelectedItem().toString();
        
        if(judul.isEmpty() || pengarang.isEmpty() || kategori.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong");
        }else{
            try{
                Connection conn = (Connection) koneksi.koneksiDB();
                Statement stt = conn.createStatement();
                stt.executeUpdate("INSERT INTO `buku`(`judul`, `pengarang`, `kategori`) VALUES ('" + judul + "', '" + pengarang + "', '" + kategori + "')");
                JOptionPane.showMessageDialog(null, "data berhasil ditambah");
                input_judul.setText(null);
                input_pengarang.setText(null);
                tampilData();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }
    
    private void tampilData() {
        try{
            Object[] judul_kolom = {"JUDUL", "PENGARANG", "KATEGORI"};
            tableModel = new DefaultTableModel(null, judul_kolom);
            table_buku.setModel(tableModel);
            
            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            RsSiswa = stt.executeQuery("SELECT * FROM buku");
            while(RsSiswa.next()){
                Object[] data = {
                    RsSiswa.getString("judul"),
                    RsSiswa.getString("pengarang"),
                    RsSiswa.getString("kategori")
                };
                tableModel.addRow(data);
            }
            
        }catch(Exception ex){
            System.err.println("gagal dek");
        }
    }
    
    private void tblKeForm() {
        int selectedRow = table_buku.getSelectedRow();
        if (selectedRow != -1) { // Pastikan baris terpilih valid
            input_judul.setText(tableModel.getValueAt(selectedRow, 0).toString());
            input_pengarang.setText(tableModel.getValueAt(selectedRow, 1).toString());

            // Temukan indeks kategori yang sesuai dalam JComboBox
            String kategori = tableModel.getValueAt(selectedRow, 2).toString();
            for (int i = 0; i < select_kategori.getItemCount(); i++) {
                if (select_kategori.getItemAt(i).equals(kategori)) {
                    select_kategori.setSelectedIndex(i);
                    break; // Setelah menemukan, keluar dari loop
                }
            }
        }
    }
    
    private void editData(){
        String judul, pengarang, kategori;
        judul = input_judul.getText();
        pengarang =  input_pengarang.getText();
        kategori =  select_kategori.getSelectedItem().toString();
        
        if(judul.isEmpty() || pengarang.isEmpty() || kategori.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }else{
            try{
                Connection conn = (Connection) koneksi.koneksiDB();
                Statement stt = conn.createStatement();
                stt.executeUpdate("UPDATE `buku` SET `judul`='" + judul + "', `pengarang`='" + pengarang + "', `kategori`='" + kategori + "' WHERE `kategori`='" + kategori + "'");
                tampilData();
                JOptionPane.showMessageDialog(null, "Data buku  " + judul + " berhasil diedit");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal diedit");
            }
        }
    }
    
    private void hapusData(){
        String judul, pengarang, kategori;
        judul = input_judul.getText();
        pengarang =  input_pengarang.getText();
        kategori =  select_kategori.getSelectedItem().toString();
        
        if(judul.isEmpty() || pengarang.isEmpty() || kategori.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
        }else{
            try{
                Connection conn = (Connection) koneksi.koneksiDB();
                Statement stt = conn.createStatement();
                stt.executeUpdate("DELETE FROM `buku` WHERE `judul`='" + judul + "'");
                tampilData();
                JOptionPane.showMessageDialog(null, "Data buku  " + judul + " berhasil dihapus");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            }
        }
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(admin_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new admin_page().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JTextField input_judul;
    private javax.swing.JTextField input_pengarang;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> select_kategori;
    private javax.swing.JTable table_buku;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
