/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Lenovo
 */
public class pinjam_buku extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    ResultSet RsSiswa = null;
    int idSiswa;

    /**
     * Creates new form pinjam_buku
     * @param idSiswa
     */
    public pinjam_buku(int idSiswa) {
        initComponents();
        tampilData();
        this.idSiswa = idSiswa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_buku = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("NeedBook");

        table_buku.setBackground(new java.awt.Color(255, 0, 51));
        table_buku.setForeground(new java.awt.Color(255, 255, 255));
        table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE_BUKU", "JUDUL", "PENGARANG", "KATEGORI"
            }
        ));
        table_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_bukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_buku);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(532, 532, 532)
                    .addComponent(jLabel1)
                    .addContainerGap(753, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jLabel1)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_bukuMouseClicked
        int opsi = JOptionPane.showConfirmDialog(null, "ingin pinjam buku ini ?", "Penghapusan Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            System.out.println(this.idSiswa);
            int row = table_buku.getSelectedRow(); // Mendapatkan indeks baris yang diklik
            if (row != -1) { // Pastikan baris yang diklik valid
                String idBuku = table_buku.getValueAt(row, 0).toString();
                System.out.println(this.idSiswa);
                try{
                    Connection conn = (Connection) koneksi.koneksiDB();
                    Statement stt = conn.createStatement();
                    stt.executeUpdate("INSERT INTO peminjaman (siswa_id, book_id) VALUES ('" + this.idSiswa + "', '" + idBuku + "')");
                    JOptionPane.showMessageDialog(null, "Buku berhasil dipinjam !");
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "gagal meminjam");
                }
            }
        }

        else
        JOptionPane.showMessageDialog(null, "Baiklah kalau tidak jadi");
    }//GEN-LAST:event_table_bukuMouseClicked

   
    private void tampilData() {
        try{
            Object[] judul_kolom = {"KODE-BUKU", "JUDUL", "PENGARANG", "KATEGORI"};
            tableModel = new DefaultTableModel(null, judul_kolom);
            table_buku.setModel(tableModel);

            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tableModel.getDataVector().removeAllElements();

            RsSiswa = stt.executeQuery("SELECT * FROM buku");
            while(RsSiswa.next()){
                Object[] data = {
                    RsSiswa.getString("id"),
                    RsSiswa.getString("judul"),
                    RsSiswa.getString("pengarang"),
                    RsSiswa.getString("kategori")
                };
                tableModel.addRow(data);
            }

            // Mengambil objek TableColumnModel dari tabel
            TableColumnModel columnModel = table_buku.getColumnModel();
            // Mengambil kolom pertama (indeks 0), yang merupakan kolom ID
            TableColumn kodeBukuColumn = columnModel.getColumn(0);
            // Mengatur lebar kolom ID menjadi 0 sehingga tidak terlihat di tabel
            kodeBukuColumn.setMinWidth(0);
            kodeBukuColumn.setMaxWidth(0);
            kodeBukuColumn.setPreferredWidth(0);

        }catch(Exception ex){
            System.err.println("error" + ex);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam_buku(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_buku;
    // End of variables declaration//GEN-END:variables
}
